[pytest]
norecursedirs = data .tox
DJANGO_SETTINGS_MODULE = drips.config.settings
django_find_project = false
addopts =
        -v
        --reuse-db
        --tb=short
        --maxfail=20
        --echo-version=drips
        --echo-version=django
        --capture=no
        --cov-report=html
        --cov-config=tests/.coveragerc
        --cov=drips

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')

[tox]
envlist = d{60}
envtmpdir={toxinidir}/build/{envname}/tmp
envlogdir={toxinidir}/build/{envname}/log

[testenv]
basepython=python3.14
passenv =
    PYTHONDONTWRITEBYTECODE
    USER
    PYTHONPATH
    DATABASE_URL
    SECRET_KEY

setenv =
    PYTHONDONTWRITEBYTECODE=true
    PYTHONPATH={toxinidir}/src
deps =
     d60: django~=6.0

allowlist_externals =
    uv
    mkdir

commands =
        mkdir -p {toxinidir}/build/results
        ruff check src/ tests/
        ruff format --check src/ tests/
        pytest tests \
            -q \
            --create-db \
            --cov-report=html \
            --cov-report=term \
            --cov-config={toxinidir}/tests/.coveragerc \
            --cov=drips

[testenv:report]
commands =
    pip install coverage
    coverage html
