refinable_properties = {
    "RefinableDate04": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_FACEFORMDATE",
        "Alias": "DRIPSFACEFORMDATE",
    },
    "RefinableDate09": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_CREATED",
        "Alias": "DRIPSCREATED",
    },
    "RefinableDate11": {
        "Type": "Date and Time",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_DATE_MODIFIED",
        "Alias": "DRIPSMODIFIED",
    },
    "RefinableString127": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FACEFORMDESCRIPTION",
        "Alias": "DRIPSFACEFORMDESCRIPTION",
    },
    "RefinableString128": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_PROGRAMDOCUMENTDESCRIPTION",
        "Alias": "DRIPSPROGRAMDOCUMENTDESCRIPTION",
    },
    "RefinableString129": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_UPLOADBY",
        "Alias": "DRIPSUPLOADEDBY",
    },
    "RefinableString13": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_PROGRAMDOCUMENTNO",
        "Alias": "DRIPSPROGRAMDOCUMENTNO",
    },
    "RefinableString130": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FACEFORMNO",
        "Alias": "DRIPSFACEFORMNO",
    },
    "RefinableString131": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_CHCS_RETRACTED",
        "Alias": "DRIPSRETRACTED",
    },
    "RefinableString132": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_HACTTRANSACTIONNO",
        "Alias": "DRIPSHACTTRANSACTIONNO",
    },
    "RefinableString133": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FUNDSCOMMITMENTNO",
        "Alias": "DRIPSFUNDSCOMMITMENTNO",
    },
    "RefinableString134": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FUNDRESERVATIONNO",
        "Alias": "DRIPSFUNDRESERVATIONNO",
    },
    "RefinableString135": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_IMPLEMENTINGPARTNERNAME",
        "Alias": "DRIPSIMPLEMENTINGPARTNERNAME",
    },
    "RefinableString136": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_HACTTRANSACTION",
        "Alias": "DRIPSHACTTRANSACTION",
    },
    "RefinableString137": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_FACEFORMTYPE",
        "Alias": "DRIPSFACEFORMTYPE",
    },
    "RefinableString138": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_DOCUMENTUPLOADEDAPP",
        "Alias": "DRIPSDOCUMENTUPLOADEDAPP",
    },
    "RefinableString139": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_HOOAPPROVAL",
        "Alias": "DRIPSHOOAPPROVAL",
    },
    "RefinableString140": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_RESPONSIBLEPERSON",
        "Alias": "DRIPSRESPONSIBLEPERSON",
    },
    "RefinableString141": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_BUSINESSAREA",
        "Alias": "DRIPSBUSINESSAREA",
    },
    "RefinableString142": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_IPTYPE",
        "Alias": "DRIPSIPTYPE",
    },
    "RefinableString143": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_CSOTYPE",
        "Alias": "DRIPSCSOTYPE",
    },
    "RefinableString144": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_RESPONSIBLEOFFICE",
        "Alias": "DRIPSRESPONSIBLEOFFICE",
    },
    "RefinableString145": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_PARTNERRISKRATING",
        "Alias": "DRIPSPARTNERRISKRATING",
    },
    "RefinableString146": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_IMPLEMENTINGPARTNERCODE",
        "Alias": "DRIPSIMPLEMENTINGPARTNERCODE",
    },
    "RefinableString147": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_BAPDOCUMENTNO",
        "Alias": "DRIPSBAPDOCUMENTNO",
    },
    "RefinableString148": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_BAPDOCUMENTTYPE",
        "Alias": "DRIPSBAPDOCUMENTTYPE",
    },
    "RefinableString149": {
        "Type": "Text",
        "Multi": "Multi",
        "Query": "Query",
        "Search": "-",
        "Retrieve": "Retrieve",
        "Refine": "Refine",
        "Sort": "Sort",
        "Safe": "Safe",
        "Mapped Crawled Property": "OWS_Q_TEXT_ATTACHMENTTYPE",
        "Alias": "DRIPSATTACHMENTTYPE",
    },
}

PROPERTY_TO_MANAGED = {
    "FACEFormDate": "RefinableDate04",
    "Created": "RefinableDate09",
    "Modified": "RefinableDate11",
    "FACEFormDescription": "RefinableString127",
    "ProgramDocumentDescription": "RefinableString128",
    "UploadedBy": "RefinableString129",
    "ProgramDocumentNo": "RefinableString13",
    "FaceFormNo": "RefinableString130",
    "Retracted": "RefinableString131",
    "HACTTransactionNo": "RefinableString132",
    "FundsCommitmentNo": "RefinableString133",
    "FundReservationNo": "RefinableString134",
    "ImplementingPartnerName": "RefinableString135",
    "HACTTransaction": "RefinableString136",
    "FaceFormType": "RefinableString137",
    "DocumentuploadedApp": "RefinableString138",
    "HoOApproval": "RefinableString139",
    "ResponsiblePerson": "RefinableString140",
    "BusinessArea": "RefinableString141",
    "IpType": "RefinableString142",
    "CsoType": "RefinableString143",
    "ResponsibleOffice": "RefinableString144",
    "PartnerRiskRating": "RefinableString145",
    "ImplementingPartnerCode": "RefinableString146",
    "BAPDocumentNo": "RefinableString147",
    "BAPDocumentType": "RefinableString148",
    "AttachmentType": "RefinableString149",
}
