# Generated by Django 4.0.6 on 2022-07-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_realm', '0001_initial'),
        ('cost_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='business_area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unicef_realm.businessarea'),
            preserve_default=False,
        ),
    ]
